name: Scrape and Deploy

on:
  schedule:
    - cron: '0 15 * * 3,6,0'  # Runs at 15:00 UTC (18:00 Helsinki time) every Wednesday, Saturday, and Sunday
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run scraper
      run: npm run update-table
      
    - name: Build React app
      run: npm run build
      
    - name: Deploy to GitHub Pages
      run: npm run deploy